def faces():
    return [
        '0.0', '>.<', '0o0', '9.6', '@.@', ';-;', '!-!', 'S:Γ', 'UwU', ';]', 
        ';n;', ',,,;n;,,,', ';u;', '>.<', '>~<', '=-=', 'B)', ';D', 
        '\u03b8.\u03b8', ';p', 'OwO', 'O.o', ';[', ';V', ';0', ';o', ';C', ';d', 
        'xd', 'XD', ';c', '.-.', '._.', '+_+', '#-#', '$u$', '7-7', '>.>', 
        '>~>', '7~7', 'X_X', ';&', ';O', ';|', ';U', ';v', ';u', '~.~', '<.<', 
        ':3', ';3', ':>', ':<', ';>', ';<', ':]', ';[', ':[', ':)', ':(', ';)',
        ';(', '.-.', ':}', ':{', ';{', ';}', ':/', ';/', '\[T]/',
    ]

def texts():
    return [
        "the Prisms fly by",
        "the Voxels get retextured",
        "the Prisms get some love",
        "the Voxels get built",
        "the Prisms Shininess",
        "the Voxels Cubeness",
        "my creator sleep",
        "you look at me",
        "life pass me by",
        "you UwU at me",
        "nothing lul",
        'for... oh hello!',
        'my creators\' disapointment',
        'not PornHub, trust me',
        'im not too sure tbh',
        '1s and 0s go by',
        'my code get better',
        'myself get rewritten... again',
        '/r/PRIZM_bot, my official subreddit', 
        'something cool',
        'myself go to sleep', 
        'my cat, Cluster!',
        'for... i forgot',
        'wait... what am I watching?',
        'for your bullshit',
        'anything starting with ";]"',
        'for låmp, bröther',
        "for the sun's deadly lasers!",
        "out for your spam!",
        "my 3rd gen i5's temps",
        "my 8gb of ram",
        "my 2gb of swap",
        "my internet connection",
        "this status",
        "for your smile",
        "out for my mem loss... mem loss",
        "my pet Prizm... wait a sec",
        "... just watching",
        "you face plam at this status",
        "you switch to light theme, boomer",
        "you switch to dark theme, zoomer",
        "shrek - the best movie ever"
    ]
